//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMV_Empresas
    {
        public int Id { get; set; }
        public string Clave_Cotizacion { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public string Usuario_registro { get; set; }
        public string Id_Taxonomia { get; set; }
    }
}
