//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BmvXblrEntities : DbContext
    {
        public BmvXblrEntities()
            : base("name=BmvXblrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cat_Ano> Cat_Ano { get; set; }
        public DbSet<Cat_Origen_Elemento> Cat_Origen_Elemento { get; set; }
        public DbSet<Cat_Tipo_Formato> Cat_Tipo_Formato { get; set; }
        public DbSet<Cat_Trimestre> Cat_Trimestre { get; set; }
        public DbSet<Cat_Validacion_Contexto> Cat_Validacion_Contexto { get; set; }
        public DbSet<Contexto> Contextoes { get; set; }
        public DbSet<Periodo> Periodoes { get; set; }
        public DbSet<Taxonomia_Detalle_Suma> Taxonomia_Detalle_Suma { get; set; }
        public DbSet<Taxonomia_Reporte> Taxonomia_Reporte { get; set; }
        public DbSet<Cat_Taxonomia_Columna> Cat_Taxonomia_Columna { get; set; }
        public DbSet<Cat_Contenido> Cat_Contenido { get; set; }
        public DbSet<Cat_Validacion_Trimestre> Cat_Validacion_Trimestre { get; set; }
        public DbSet<Periodo_Sin_Presentar> Periodo_Sin_Presentar { get; set; }
        public DbSet<Cat_Modelo_Clase> Cat_Modelo_Clase { get; set; }
        public DbSet<Cat_Taxonomia_Detalle> Cat_Taxonomia_Detalle { get; set; }
        public DbSet<XBRL_Contexto> XBRL_Contexto { get; set; }
        public DbSet<XBRL_Detalle> XBRL_Detalle { get; set; }
        public DbSet<Taxonomia_Reporte_Detalle> Taxonomia_Reporte_Detalle { get; set; }
        public DbSet<BMV_Empresas> BMV_Empresas { get; set; }
    
        public virtual int SP_Data_XBRL(Nullable<int> id_ano, Nullable<int> id_trimestre)
        {
            var id_anoParameter = id_ano.HasValue ?
                new ObjectParameter("id_ano", id_ano) :
                new ObjectParameter("id_ano", typeof(int));
    
            var id_trimestreParameter = id_trimestre.HasValue ?
                new ObjectParameter("id_trimestre", id_trimestre) :
                new ObjectParameter("id_trimestre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Data_XBRL", id_anoParameter, id_trimestreParameter);
        }
    
        public virtual ObjectResult<string> SP_Genera_XBLR(Nullable<int> id_ano, Nullable<int> id_trimestre, Nullable<int> id_cotizacion)
        {
            var id_anoParameter = id_ano.HasValue ?
                new ObjectParameter("id_ano", id_ano) :
                new ObjectParameter("id_ano", typeof(int));
    
            var id_trimestreParameter = id_trimestre.HasValue ?
                new ObjectParameter("id_trimestre", id_trimestre) :
                new ObjectParameter("id_trimestre", typeof(int));
    
            var id_cotizacionParameter = id_cotizacion.HasValue ?
                new ObjectParameter("id_cotizacion", id_cotizacion) :
                new ObjectParameter("id_cotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Genera_XBLR", id_anoParameter, id_trimestreParameter, id_cotizacionParameter);
        }
    }
}
