//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Validacion_Trimestre
    {
        public int Id_Contexto_Periodo { get; set; }
        public Nullable<int> Id_Validacion_Contexto { get; set; }
        public Nullable<int> Id_Trimestre { get; set; }
        public string Dia_Ini { get; set; }
        public string Mes_Ini { get; set; }
        public string Dia_Final { get; set; }
        public string Mes_Final { get; set; }
    
        public virtual Cat_Trimestre Cat_Trimestre { get; set; }
    }
}
