//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Contenido
    {
        public Cat_Contenido()
        {
            this.Cat_Taxonomia_Columna = new HashSet<Cat_Taxonomia_Columna>();
            this.Taxonomia_Detalle_Suma = new HashSet<Taxonomia_Detalle_Suma>();
            this.Taxonomia_Reporte = new HashSet<Taxonomia_Reporte>();
        }
    
        public int Id_Contenido { get; set; }
        public string Contenido { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Cat_Taxonomia_Columna> Cat_Taxonomia_Columna { get; set; }
        public virtual ICollection<Taxonomia_Detalle_Suma> Taxonomia_Detalle_Suma { get; set; }
        public virtual ICollection<Taxonomia_Reporte> Taxonomia_Reporte { get; set; }
    }
}
