//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Origen_Elemento
    {
        public Cat_Origen_Elemento()
        {
            this.Cat_Taxonomia_Detalle = new HashSet<Cat_Taxonomia_Detalle>();
        }
    
        public int Id_Origen_Elemento { get; set; }
        public string Prefijo { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<Cat_Taxonomia_Detalle> Cat_Taxonomia_Detalle { get; set; }
    }
}
