//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Modelo_Clase
    {
        public Cat_Modelo_Clase()
        {
            this.Cat_Taxonomia_Columna = new HashSet<Cat_Taxonomia_Columna>();
        }
    
        public int Id_Modelo_Clase { get; set; }
        public string Atributo { get; set; }
        public Nullable<int> Id_Taxonomia_Detalle_Axis_X { get; set; }
        public Nullable<int> Id_Taxonomia_Detalle_Axis_Y { get; set; }
    
        public virtual Cat_Taxonomia_Detalle Cat_Taxonomia_Detalle { get; set; }
        public virtual Cat_Taxonomia_Detalle Cat_Taxonomia_Detalle1 { get; set; }
        public virtual ICollection<Cat_Taxonomia_Columna> Cat_Taxonomia_Columna { get; set; }
    }
}
