//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Taxonomia_Columna
    {
        public Cat_Taxonomia_Columna()
        {
            this.Taxonomia_Reporte = new HashSet<Taxonomia_Reporte>();
        }
    
        public int Id_Taxonomia_Columna { get; set; }
        public Nullable<int> Id_Contenido { get; set; }
        public Nullable<int> Id_Modelo_Clase { get; set; }
        public Nullable<int> Id_Taxonomia_Detalle { get; set; }
        public Nullable<int> Id_Validacion_Contexto { get; set; }
    
        public virtual Cat_Validacion_Contexto Cat_Validacion_Contexto { get; set; }
        public virtual ICollection<Taxonomia_Reporte> Taxonomia_Reporte { get; set; }
        public virtual Cat_Contenido Cat_Contenido { get; set; }
        public virtual Cat_Modelo_Clase Cat_Modelo_Clase { get; set; }
        public virtual Cat_Taxonomia_Detalle Cat_Taxonomia_Detalle { get; set; }
    }
}
