//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        public Periodo()
        {
            this.Contextoes = new HashSet<Contexto>();
        }
    
        public int Id_Periodo { get; set; }
        public Nullable<int> Id_Validacion_Contexto { get; set; }
        public Nullable<int> Id_Trimestre { get; set; }
        public Nullable<int> Id_Ano { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
    
        public virtual Cat_Ano Cat_Ano { get; set; }
        public virtual Cat_Trimestre Cat_Trimestre { get; set; }
        public virtual Cat_Validacion_Contexto Cat_Validacion_Contexto { get; set; }
        public virtual ICollection<Contexto> Contextoes { get; set; }
    }
}
