//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxonomia_Reporte_Detalle
    {
        public int Id_Taxonomia_Reporte_Detalle { get; set; }
        public Nullable<int> Id_Taxonomia_Reporte { get; set; }
        public Nullable<int> Id_Contexto { get; set; }
        public Nullable<int> Id_Trimestre { get; set; }
        public Nullable<int> Id_Ano { get; set; }
        public string Valor { get; set; }
        public Nullable<int> Identificador_Fila { get; set; }
        public Nullable<System.DateTime> Fecha_Guardado { get; set; }
        public Nullable<System.DateTime> Fecha_Ultima_Actualizacion { get; set; }
    
        public virtual Cat_Ano Cat_Ano { get; set; }
        public virtual Cat_Trimestre Cat_Trimestre { get; set; }
        public virtual Contexto Contexto { get; set; }
        public virtual Taxonomia_Reporte Taxonomia_Reporte { get; set; }
    }
}
