//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxonomia_Detalle_Suma
    {
        public int Id_Taxonomia_Suma { get; set; }
        public Nullable<int> Id_Taxonomia_Detalle_Padre { get; set; }
        public Nullable<int> Id_Taxonomia_Detalle_Hijo { get; set; }
        public Nullable<int> Id_Contenido { get; set; }
    
        public virtual Cat_Contenido Cat_Contenido { get; set; }
        public virtual Cat_Taxonomia_Detalle Cat_Taxonomia_Detalle { get; set; }
        public virtual Cat_Taxonomia_Detalle Cat_Taxonomia_Detalle1 { get; set; }
    }
}
