//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XBRL_Detalle
    {
        public int Id_ano { get; set; }
        public int Id_trimestre { get; set; }
        public int Id_XBRL_Contexto { get; set; }
        public int Id_XBRL_Detalle { get; set; }
        public Nullable<int> Id_contenido { get; set; }
        public string Contenido { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Formato { get; set; }
        public string Referencia_Tiempo { get; set; }
        public string Prefijo { get; set; }
        public string Atributo { get; set; }
        public string Valor { get; set; }
        public string Descripcion { get; set; }
        public string Nombre_esquema { get; set; }
        public string EsquemaX { get; set; }
        public string EsquemaY { get; set; }
        public string EsquemaXCabecera { get; set; }
        public string EsquemaYCabecera { get; set; }
        public Nullable<int> Identificador_Fila { get; set; }
        public Nullable<int> Id_Validacion_Contexto { get; set; }
        public string Fecha_inicial { get; set; }
        public string Fecha_final { get; set; }
    }
}
