//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxonomiaWeb.Wcf.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XBRL_Contexto
    {
        public int Id_Ano { get; set; }
        public int Id_Trimestre { get; set; }
        public int Id_XBRL_Contexto { get; set; }
        public string ReferenciaTiempo { get; set; }
        public string Prefijo { get; set; }
        public string EsquemaX { get; set; }
        public string EsquemaY { get; set; }
        public string EsquemaCabeceraX { get; set; }
        public string EsquemaCabeceraY { get; set; }
        public string Nombre_Esquema { get; set; }
        public string TypedMember { get; set; }
        public string TypedMember_Valor { get; set; }
        public string TypedMember2 { get; set; }
        public string TypedMember2_Valor { get; set; }
        public Nullable<int> Identificador_Fila { get; set; }
        public string FechaInicial { get; set; }
        public string FechaFinal { get; set; }
    }
}
